### ISSUE TITLE
VS2022社区版安装不成功

### ISSUE THREAD

**Issue by ruoleng** [genrwoody/vs_file_encoding#3]
报错日志：
VSIXInstaller.NoApplicableSKUsException: 此扩展不能安装在任何当前安装的产品上

VS版本
Microsoft Visual Studio Community 2022  (64 位) - Current
版本 17.3.3

**Comment by genrwoody** [comment]
我在插件市场上传了两个版本的插件，一个是2019，一个是2022。
请确认你下载的版本是否正确，VS2022从这个网址下载：
https://marketplace.visualstudio.com/items?itemName=genrwoody.FileEncodingVS2022

**Comment by ruoleng** [comment]
> 我在插件市场上传了两个版本的插件，一个是2019，一个是2022。 请确认你下载的版本是否正确，VS2022从这个网址下载： https://marketplace.visualstudio.com/items?itemName=genrwoody.FileEncodingVS2022

确认是2022的版本，安装失败，搞不明白。办公电脑安装不了，好像家里的安装得了。
