### ISSUE TITLE
全英文的文件打开后会识别为GB2312

### ISSUE THREAD

**Issue by goxigo** [genrwoody/vs_file_encoding#5]

**Comment by bebuch** [comment]
Pure ASCII files should default to UTF8, not to the local encoding.

**Comment by bebuch** [comment]
I have just seen that you have also described this in the README. Please use English. I wouldn't have seen it without translation software. English is understood by all developers worldwide. If you like, I can make a pull request.

**Comment by genrwoody** [comment]
@bebuch Thank you for the feedback. The English README has been added.

**Comment by genrwoody** [comment]
在1.0.5版本中把系统编码显示为SYS.
