### ISSUE TITLE
希望支持 Windows On Arm 的 Visual Studio 2022

### ISSUE THREAD

**Issue by Alan-CRL** [genrwoody/vs_file_encoding#6]
当前的拓展是只兼容 amd64 架构的，希望能考虑一下 arm64

**Comment by genrwoody** [comment]
感谢反馈.
增加了arm64的安装目标, 我没有arm64的机器, 请帮忙测试一下.
由于网络问题, 扩展市场还没有更新, 我把最新的插件放到release中了, 可以先手动安装试试.
https://github.com/genrwoody/vs_file_encoding/releases/download/1.0.4/FileEncoding.vsix

**Comment by Alan-CRL** [comment]
经过测试，安装和编码显示一切正常
